export const orderSteps = [
    "are_gerbers_generated",
    "are_gerbers_uploaded",
    "is_gerber_analyzed",
    "are_initial_costs_calculated",
    "is_pcb_added_to_cart",
    "is_bom_uploaded",
    "is_pnp_uploaded",
    "is_bom_pnp_analyzed",
    "is_bom_parsing_complete",
    "are_components_available",
    "is_patch_map_generated",
    "is_json_merge_file_created",
    "is_dfm_result_generated",
    "are_files_downloaded",
    "are_product_categories_fetched",
    "are_final_costs_calculated",
    "is_json_merge_file_updated",
    "is_added_to_cart",
] as const